spring:
  application:
    name: flujos-trabajo-documentacion
  datasource:
    url: jdbc:postgresql://localhost:5432/ssoma_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 8084
  servlet:
    session:
      timeout: 30m

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    com.dataservices.ssoma.flujos_trabajo_documentacion: DEBUG
    org.springframework.security: INFO
    org.springdoc: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"